version: '2'
services:
  app:
    build: 
      context: ./app
    command: npm run dev
    
  #  volumes:
   #   - .:/usr/app/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    
    environment:
      DATABASE_URL: 

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"