version: '3'
services:
  app:
    build: 
      context: ./app
    command: npm run dev
    
    # volumes:
    #  - .:/usr/app/app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    
    environment:
      DATABASE_URL: 
  
  frontend:
    build: 
      context: pinboard # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port mapping
    links:
      - app
       
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"